
language: node_js
node_js:    
  - "12"
addons:
  chrome: stable   
before_script:
  - npm install 
jobs:
  include:
    - stage: Test coverage
      script:
        - npm test 
        - npm run codecov
      after_success:
         - bash <(curl -s https://codecov.io/bash)
